# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='student_number_cap',
        ),
        migrations.AlterField(
            model_name='homework',
            name='assign_date',
            field=models.DateField(verbose_name='布置日期'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='completed_student',
            field=models.ManyToManyField(blank=True, related_name='completed_homework', to='mainsite.Student', verbose_name='已完成的学生'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateField(verbose_name='截止日期'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='homework_content',
            field=models.TextField(max_length=5000, verbose_name='作业内容'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='submission',
            field=models.CharField(choices=[('Submit by Email', 'Submit by Email'), ('Submit in Person', 'Submit in Person'), ('Submit by Wechat', 'Submit by Wechat'), ('Submit in Class', 'Submit in Class'), ('No need to Submit', 'No need to Submit')], default='Submit by Wechat', max_length=20, verbose_name='提交方式'),
        ),
    ]
